lines = [
    '# -*- coding: utf-8 -*-',
    'import json, time',
    'from services.notion import get_all_tasks, search_tasks, get_handover_data, notion_client, _parse_task, get_my_tasks',
    'from services.slack import build_log_step_modal, build_task_select_modal, build_handover_message, build_error_message',
    '',
    'def register_actions(app):',
    '',
    '    @app.action("open_ilji_modal")',
    '    def handle_open_ilji_modal(ack, body, client, logger):',
    '        ack()',
    '        try:',
    '            lv = {"type":"modal","title":{"type":"plain_text","text":"업무일지 작성"},"close":{"type":"plain_text","text":"취소"},"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"로딩중..."}}]}',
    '            resp = client.views_open(trigger_id=body["trigger_id"],view=lv)',
    '            vid = resp["view"]["id"]',
    '            uid = body.get("user",{}).get("id")',
    '            try:',
    '                ui = client.users_info(user=uid)',
    '                rn = ui["user"]["profile"].get("real_name","")',
    '            except:',
    '                rn = ""',
    '            if rn:',
    '                tasks = get_my_tasks(rn)',
    '                if len(tasks) < 5:',
    '                    at = get_all_tasks()',
    '                    eids = {t["id"] for t in tasks}',
    '                    for t in at:',
    '                        if t["id"] not in eids:',
    '                            tasks.append(t)',
    '                            if len(tasks) >= 9: break',
    '            else:',
    '                tasks = get_all_tasks()',
    '            logger.info(f"tasks={len(tasks)} user={rn}")',
    '            client.views_update(view_id=vid, view=build_task_select_modal(tasks))',
    '        except Exception as e: logger.error(f"modal err: {e}")',
    '',
    '    @app.action("search_keyword")',
    '    def handle_search_keyword(ack, body, client, logger):',
    '        ack()',
    '        try:',
    '            view=body["view"]; vid=view["id"]; vals=view["state"]["values"]',
    '            kw=(vals.get("block_search",{}).get("search_keyword",{}).get("value","") or "").strip()',
    '            if not kw: return',
    '            tasks=search_tasks(kw)',
    '            logger.info(f"search {kw}: {len(tasks)}")',
    '            client.views_update(view_id=vid, view=build_task_select_modal(tasks, search_keyword=kw))',
    '        except Exception as e: logger.error(f"search err: {e}")',
    '',
    '    @app.action("task_checkboxes")',
    '    def handle_task_checkboxes_action(ack, body, logger): ack()',
    '',
    '    @app.view("modal_task_select")',
    '    def handle_task_select(ack, body, client, logger):',
    '        try:',
    '            vals=body["view"]["state"]["values"]',
    '            sel=vals["block_task_select"]["task_checkboxes"]["selected_options"]',
    '            if not sel:',
    '                ack(response_action="errors",errors={"block_task_select":"Task를 선택해 주세요."}); return',
    '            tasks=[{"id":o["value"],"name":o["text"]["text"]} for o in sel]',
    '            meta=json.dumps({"tasks":tasks,"current":0,"done":[]},ensure_ascii=False)',
    '            f=tasks[0]; is_new=(f["id"]=="NEW_TASK")',
    '            modal=build_log_step_modal(metadata_json=meta,task_name=f["name"],step=1,total=len(tasks),is_new=is_new)',
    '            ack(response_action="push",view=modal)',
    '        except Exception as e:',
    '            logger.error(f"task select err: {e}")',
    '            ack(response_action="errors",errors={"block_task_select":"오류 발생."})',
    '',
    '    @app.view("modal_handover_select")',
    '    def handle_handover_select(ack, body, client, logger):',
    '        ack()',
    '        uid=body.get("user",{}).get("id")',
    '        vals=body["view"]["state"]["values"]',
    '        sel=vals["block_handover_task"]["handover_task_select"]["selected_option"]',
    '        if not sel:',
    '            if uid: client.chat_postMessage(channel=uid,blocks=build_error_message("Task 선택 필요."))',
    '            return',
    '        tid=sel["value"]; tlabel=sel["text"]["text"]',
    '        logger.info(f"handover: {tlabel}")',
    '        try:',
    '            page=notion_client.pages.retrieve(page_id=tid)',
    '            task=_parse_task(page)',
    '            time.sleep(0.35)',
    '            logs=get_handover_data(tid)',
    '            blocks=build_handover_message(task,logs)',
    '            client.chat_postMessage(channel=uid,text="인수인계 초안",blocks=blocks)',
    '        except Exception as e:',
    '            logger.error(f"handover err: {e}")',
    '            if uid: client.chat_postMessage(channel=uid,blocks=build_error_message(str(e)))',
]

with open(r'c:\Users\user\공간환경계획연구실 Dropbox\04_Knowledge_Base\00_Obsidian\moon\03_task_및_업무일지_관리\narae-bot\handlers\action.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

import ast
ast.parse(open(r'c:\Users\user\공간환경계획연구실 Dropbox\04_Knowledge_Base\00_Obsidian\moon\03_task_및_업무일지_관리\narae-bot\handlers\action.py', encoding='utf-8').read())
print('OK - action.py written')
